# Generated by Django 4.1.3 on 2022-11-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_prodect_options_prodect_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('waitingapproval', 'waitingapproval'), ('active', 'active'), ('deleted', 'deleted')], default='active', max_length=50),
        ),
    ]
