# Generated by Django 4.1.3 on 2022-11-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_prodect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodect',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product_images/thumbnail'),
        ),
    ]
